#17 Replace flannel as CNI with cilium

diff --git a/.taskfiles/TalosTasks.yml b/.taskfiles/TalosTasks.yml
--- a/.taskfiles/TalosTasks.yml
+++ b/.taskfiles/TalosTasks.yml
@@ -2,7 +2,7 @@
 version: "3"
 
 tasks:
-
+  silent: true
   init:
     desc: Generate and validate configuration files
     dir: "{{.TALOS_DIR}}"
@@ -21,7 +21,7 @@ tasks:
     desc: Generate base configuration files and encrypt
     dir: "{{.TALOS_DIR}}"
     cmds:
-      - talosctl gen config homelab-{{.BOOTSTRAP_GIT_BRANCH}}-cluster https://{{.BOOTSTRAP_KUBE_VIP_ADDR}}:6443 --config-patch-control-plane @cp.patch.yaml --config-patch @all.patch.yaml {{.CLI_ARGS}}
+      - talosctl gen config homelab-{{.BOOTSTRAP_ENV}}-cluster https://{{.BOOTSTRAP_KUBE_VIP_ADDR}}:6443 --config-patch-control-plane @cp.patch.yaml --config-patch @all.patch.yaml {{.CLI_ARGS}}
       - mv controlplane.yaml controlplane.sops.yaml
       - mv worker.yaml worker.sops.yaml
       - mv talosconfig {{.ROOT_DIR}}/talosconfig
@@ -46,31 +46,37 @@ tasks:
     dir: "{{.TALOS_DIR}}"
     cmds:
       - task: create-vms
+        silent: true
         ignore_error: true  # hacky way to make this command optional
-      - task: ping
+      - task: ping-cluster
+        vars: { NODES: all, PORT: 50000 }
+      - task: ping-cluster
+        vars: { NODES: control, PORT: 50001 }
       - echo "Bootstrapping the cluster..."
       - talosctl bootstrap -e {{.BOOTSTRAP_TALOS_HOST_ADDR_0}} -n {{.BOOTSTRAP_TALOS_HOST_ADDR_0}}
       - talosctl config endpoint {{.BOOTSTRAP_TALOS_HOST_ADDR_0}}
       - talosctl config node {{.BOOTSTRAP_TALOS_HOST_ADDR_0}}
+      - task: ping-cluster
+        vars: { NODES: all, PORT: 50000 }
+      - task: ping-cluster
+        vars: { NODES: control, PORT: 50001 }
       - talosctl kubeconfig {{.ROOT_DIR}}
-      - echo "Cluster bootstrap successful. The kubeconfig has been copied to '{{.ROOT_DIR}}'"
-
-  configure-vmtoolsd:
-    desc: Provide a talos credentails file for the talos-vmtoolsd daemonset to use.
-    dir: "{{.TALOS_DIR}}"
-    cmds:
-      - echo "Configuring talos-vmtoolsd..."
-      - talosctl -n {{.BOOTSTRAP_TALOS_HOST_ADDR_0}} config new vmtoolsd-secret.yaml --roles os:admin
-      - kubectl -n kube-system create secret generic talos-vmtoolsd-config --from-file=talosconfig=./vmtoolsd-secret.yaml
-      - rm -f vmtoolsd-secret.yaml
-      - echo "talos-vmtoolsd configured successfully."
+      - echo "The kubeconfig has been copied to '{{.ROOT_DIR}}'"
+      - echo "Waiting for control plane to become available..."
+      - task: ping-cluster
+        vars: { NODES: control, PORT: 6443 }
+      - task: deploy-cilium
+      - echo "Waiting for cluster to be healthy..."
+      - talosctl health
+      - echo "Cluster bootstrap successful."
 
   create-vms:
-    desc: (Development only) Create VMs for talos cluster
+    silent: true
+    desc: (Staging only) Create VMs for talos cluster
     dir: "{{.TALOS_DIR}}"
     preconditions:
-      - sh: '[ "${BOOTSTRAP_GIT_BRANCH}" = "development" ]'
-        msg: "Skipping VM creation, because the environment is not 'development'."
+      - sh: '[ "${BOOTSTRAP_ENV}" = "staging" ]'
+        msg: "Skipping VM creation, because the environment is not 'staging'."
       - sh: test -f {{.TALOS_DIR}}/controlplane.sops.yaml
         msg: |
           Control plane machine config was not found. Did you forget to create it?
@@ -78,7 +84,7 @@ tasks:
         msg: |
           Worker machine config was not found. Did you forget to create it?
     cmds:
-      - echo "Creating VMs for development environment..."
+      - echo "Creating VMs for staging environment..."
       - task: :terraform:vsphere-init
       - cmd: task terraform:vsphere-apply -- -auto-approve -var="control_machine_config={{.ENCODED_CONTROL_CONFIG}}" -var="worker_machine_config={{.ENCODED_WORKER_CONFIG}}"
         silent: true
@@ -88,31 +94,111 @@ tasks:
       ENCODED_WORKER_CONFIG:
         sh: sops --decrypt {{.TALOS_DIR}}/worker.sops.yaml | base64
 
-  ping:
-    silent: true
-    desc: Test talosctl connectivity to each node
+  deploy-cilium:
+    internal: true
+    desc: Deploy Cilium CNI (with kube-proxy)
     dir: "{{.TALOS_DIR}}"
     cmds:
-      - echo "Testing node connectivity..."
+      - echo "Attemping to deploy Cilium..."
+      - echo "Checking prerequisites..."
+      - task: cilium-prereqs
+      - echo "Deploying Cilium..."
+      - |
+        helm template \
+            cilium \
+            cilium/cilium \
+            --version 1.15.6 \
+            --namespace kube-system \
+            --set ipam.mode=kubernetes \
+            --set kubeProxyReplacement=false \
+            --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
+            --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
+            --set cgroup.autoMount.enabled=false \
+            --set cgroup.hostRoot=/sys/fs/cgroup > cilium.yaml
+      - kubectl apply -f cilium.yaml
+      - rm -f cilium.yaml
+
+  cilium-prereqs:
+    internal: true
+    desc: Checks for helm repo and machine config
+    dir: "{{.TALOS_DIR}}"
+    cmds:
+      - echo "Checking for cilium helm repo..."
+      - |
+        if [[ ! $(helm repo list | grep cilium) ]]; then
+          helm repo add cilium https://helm.cilium.io
+          helm repo update
+        fi
+        echo "Cilium helm repo located."
+      - echo "Checking for valid machine config..."
+      - |
+        if [[ "$(sops -d controlplane.sops.yaml | yq '.cluster.network.cni.name')" != "none" ]]; then
+          echo "Control plane machine config does not have CNI set to 'none'. Did you forget to run 'task talos:init'?"
+          exit 1
+        fi
+        echo "Control plane machine config verified."
+        if [[ "$(sops -d worker.sops.yaml | yq '.cluster.network.cni.name')" != "none" ]]; then
+          echo "Worker machine config does not have CNI set to 'none'. Did you forget to run 'task talos:init'?"
+          exit 1
+        fi
+        echo "Worker machine config verified."
+    preconditions:
+      - sh: test -f {{.SOPS_AGE_KEY_FILE}}
+        msg: |
+          Age key file is not found. Did you forget to create it?
+    vars:
+      SOPS_AGE_KEY_FILE: ~/.config/sops/age/keys.txt
+
+  ping-cluster:
+    silent: true
+    desc: 'Tests connectivity specified hosts and TCP port'
+    dir: "{{.TALOS_DIR}}"
+    cmds:
+      - echo "Testing {{.NODES}} connectivity..."
       - |
         host_reachable=false
         for var in "${!BOOTSTRAP_TALOS_HOST_ADDR_@}"; do
-          for i in {1..{{.PING_MAX_ATTEMPTS}}}; do
-            if nc -z "${!var}" 50000 &> /dev/null; then
-              echo "Node at ${!var} is reachable at TCP 50000."
-              host_reachable=true
-              break
-            else
-              echo "Node at ${!var} is not reachable yet. Retrying in {{.PING_SLEEP}} seconds..."
-              sleep {{.PING_SLEEP}}
-            fi
-          done
-          if [[ "$host_reachable" == false ]]; then
-            echo "ERROR: Node at ${!var} is unreachable after {{.PING_MAX_ATTEMPTS}} attempts."
-            exit 1
+          node_id="${var##*_}"
+          node_control="BOOTSTRAP_TALOS_CONTROL_NODE_${node_id}"
+          if [[ {{.NODES}} == "all" ]]; then
+            task talos:tcp-ping HOST=${!var} PORT={{.PORT}}
+          elif [[ "${!node_control}" == "true" && {{.NODES}} == "control" ]]; then
+            task talos:tcp-ping HOST=${!var} PORT={{.PORT}}
+          elif [[ "${!node_control}" == "false" && {{.NODES}} == "worker" ]]; then
+            task talos:tcp-ping HOST=${!var} PORT={{.PORT}}
+          else
+            continue
           fi
         done
-      - echo "All nodes are reachable."
+    requires:
+      vars:
+        - name: NODES
+          enum: [all, control, worker]
+        - name: PORT
+
+  tcp-ping:
+    silent: true
+    desc: Tests connection to TCP 'PORT' at 'HOST'
+    dir: "{{.TALOS_DIR}}"
+    cmds:
+      - |
+        host_reachable=false
+        for i in {1..{{.PING_MAX_ATTEMPTS}}}; do
+          if nc -z {{.HOST}} {{.PORT}} &> /dev/null; then
+            echo "Host at {{.HOST}} is reachable at TCP {{.PORT}}."
+            host_reachable=true
+            break
+          else
+            echo "Host at {{.HOST}} is not reachable yet. Retrying in {{.PING_SLEEP}} seconds..."
+            sleep {{.PING_SLEEP}}
+          fi
+        done
+        if [[ "$host_reachable" == false ]]; then
+          echo "ERROR: Node at {{.HOST}} is unreachable after {{.PING_MAX_ATTEMPTS}} attempts."
+          exit 1
+        fi
     vars:
       PING_MAX_ATTEMPTS: 5
       PING_SLEEP: 10
+      HOST: '{{.HOST}}'
+      PORT: '{{.PORT}}'
